sudo: false
language: node_js
node_js:
    - "10"
    - "13"
cache:
    directories:
        - node_modules
script:
    - yarn build
jobs:
    include:
      - stage: "Tests"
        name: "Jest tests"
        script: yarn run jest
      - name: "ESLint"
        script: yarn run eslint